version: '3'
services:
  amneziawg_client:
    container_name: amneziawg_client
    build: amneziawg-client
    cap_add:
      - NET_ADMIN
    volumes:
      - ./amneziawg-client.conf:/etc/amnezia/amneziawg/wg0.conf
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/newip.dat"]
      interval: 10s
      timeout: 1s
      retries: 10
#  amneziawg_client:
#    container_name: amneziawg_client
#    build: sing-box-client
#    restart: unless-stopped
#    cap_add:
#      - NET_ADMIN
#    volumes:
#      - ./xray-client.json:/app/input.json:ro
##    ports:
##      - "127.0.0.1:1080:1080"
##      - "127.0.0.1:8080:8080"
#    devices:
#      - /dev/net/tun
#    healthcheck:
#      test: ["CMD", "test", "-f", "/tmp/newip.dat"]
#      interval: 10s
#      timeout: 1s
#      retries: 10
  openvpn_server_with_tls:
    container_name: openvpn_server_with_tls
    build: openvpn-server-with-tls
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
      - "8080:8080/tcp"
    environment:
      HOST_CONF_PORT: "8080"
      HOST_TUN_PORT: "1194"
      HOST_ADDR: "192.168.1.2"
    depends_on:
      amneziawg_client:
        condition: service_healthy
    volumes:
      - ./openvpn-server-with-tls.conf:/opt/Dockovpn_data
    stdin_open: true                  # eq -i
    tty: true                         # rq -t
    restart: "no"
  openvpn_server_no_tls:
    container_name: openvpn_server_no_tls
    build: openvpn-server-no-tls
    cap_add:
      - NET_ADMIN
    ports:
      - "1195:1195/udp"
      - "8081:8081/tcp"
    environment:
      HOST_CONF_PORT: "8081"
      HOST_TUN_PORT: "1195"
      HOST_ADDR: "192.168.1.2"
    volumes:
      - ./openvpn-server-no-tls.conf:/opt/Dockovpn_data
    depends_on:
      amneziawg_client:
        condition: service_healthy
    stdin_open: true                  # eq -i
    tty: true                         # eq -t
    restart: "no"
#  openvpn_server_no_tls_pass:
#    container_name: openvpn_server_no_tls_pass
#    build: openvpn-server-no-tls-pass
#    cap_add:
#      - NET_ADMIN
#    ports:
#      - "1196:1196/tcp"
#      - "8082:8082/tcp"
#    environment:
#      HOST_CONF_PORT: "8082"
#      HOST_TUN_PORT: "1196"
#      HOST_ADDR: "192.168.1.2"
#    volumes:
#      - ./openvpn-server-no-tls-pass.conf:/opt/Dockovpn_data
#      - ./psw-file:/etc/openvpn/psw-file:ro
#    depends_on:
#      amneziawg_client:
#        condition: service_healthy
#    stdin_open: true                  # eq -i
#    tty: true                         # eq -t
#    restart: "no"
